plugins:
  - babel
  - jest
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
rules:
  no-console: 0
  no-unused-vars: [error, {argsIgnorePattern: "^_|err|next"}]
